[package]
name = "learning_rust_myelf"
version = "0.0.1"
authors = ["Peter Bartha <peitur@gmail.com>" ]
eddition = "2019"

[dependencies]
mio = "0.6"
rustls = "0.16"
tokio = "0.1"
serde_json = "1.0"
bytes = "0.4"
regex = "1.3"
